### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [cjferna/Photo-Services-Mashup#1]
Hey there!

I belong to an open source security research community, and a member (@cyphercoda) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by cjferna** [comment]
Hello there!

Thanks for your advice. I added the SECURITY.md and I am looking forward about receiving information from your teammate.

Thank you both for the information, I really appreciate it.

**Comment by JamieSlome** [comment]
@cjferna - great! 👍 In the meantime, you can view the report directly here:

https://huntr.dev/bounties/b1a0647e-d2b7-41cf-944d-41114f83a504/

It is private and only visible to you ❤️

**Comment by cjferna** [comment]
Thanks you very much for reporting. The issue is now fixed, keys has been withdrew and the history of the affected files has been removed. 

The ticket on huntr.dev has been also marked as solved.
